### ISSUE TITLE
Google drive links: quota exceeded

### ISSUE THREAD

**Issue by lhoestq** [armancohan/long-summarization#14]
Hi !
Sometimes when trying to download the dataset we can get an error from google drive "Quota Exceeded". This happens when the files have been downloaded too many times in the last 24h.
Is there a mirror link somewhere that is not using google drive ?
Thanks in advance :)

**Comment by Franck-Dernoncourt** [comment]
https://archive.org/details/armancohan-long-summarization-paper-code

**Comment by lhoestq** [comment]
Thank you

**Comment by lhoestq** [comment]
Is this ok if we also host the files on hugging face S3 ? This way we can workaround the google drive quota limit and keeping a better download speed than the archive.org link

**Comment by armancohan** [comment]
Sure. That would be great.

**Comment by Franck-Dernoncourt** [comment]
Thanks Quentin! Happy new year to the Hugging Face team :-)
